package agrar.dict.sbuilder.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the DictArea service. Represents a row in the &quot;agrar_dict_DictArea&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link agrar.dict.sbuilder.model.impl.DictAreaModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link agrar.dict.sbuilder.model.impl.DictAreaImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DictArea
 * @see agrar.dict.sbuilder.model.impl.DictAreaImpl
 * @see agrar.dict.sbuilder.model.impl.DictAreaModelImpl
 * @generated
 */
public interface DictAreaModel extends BaseModel<DictArea> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a dict area model instance should use the {@link DictArea} interface instead.
     */

    /**
     * Returns the primary key of this dict area.
     *
     * @return the primary key of this dict area
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this dict area.
     *
     * @param primaryKey the primary key of this dict area
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the ID of this dict area.
     *
     * @return the ID of this dict area
     */
    public long getId();

    /**
     * Sets the ID of this dict area.
     *
     * @param id the ID of this dict area
     */
    public void setId(long id);

    /**
     * Returns the archive of this dict area.
     *
     * @return the archive of this dict area
     */
    public boolean getArchive();

    /**
     * Returns <code>true</code> if this dict area is archive.
     *
     * @return <code>true</code> if this dict area is archive; <code>false</code> otherwise
     */
    public boolean isArchive();

    /**
     * Sets whether this dict area is archive.
     *
     * @param archive the archive of this dict area
     */
    public void setArchive(boolean archive);

    /**
     * Returns the code of this dict area.
     *
     * @return the code of this dict area
     */
    public long getCode();

    /**
     * Sets the code of this dict area.
     *
     * @param code the code of this dict area
     */
    public void setCode(long code);

    /**
     * Returns the name of this dict area.
     *
     * @return the name of this dict area
     */
    @AutoEscape
    public String getName();

    /**
     * Sets the name of this dict area.
     *
     * @param name the name of this dict area
     */
    public void setName(String name);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(agrar.dict.sbuilder.model.DictArea dictArea);

    @Override
    public int hashCode();

    @Override
    public CacheModel<agrar.dict.sbuilder.model.DictArea> toCacheModel();

    @Override
    public agrar.dict.sbuilder.model.DictArea toEscapedModel();

    @Override
    public agrar.dict.sbuilder.model.DictArea toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
