package agrar.farmer.sbuilder.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the FarmerArea service. Represents a row in the &quot;agrar_farmer_FarmerArea&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link agrar.farmer.sbuilder.model.impl.FarmerAreaModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link agrar.farmer.sbuilder.model.impl.FarmerAreaImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see FarmerArea
 * @see agrar.farmer.sbuilder.model.impl.FarmerAreaImpl
 * @see agrar.farmer.sbuilder.model.impl.FarmerAreaModelImpl
 * @generated
 */
public interface FarmerAreaModel extends BaseModel<FarmerArea> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a farmer area model instance should use the {@link FarmerArea} interface instead.
     */

    /**
     * Returns the primary key of this farmer area.
     *
     * @return the primary key of this farmer area
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this farmer area.
     *
     * @param primaryKey the primary key of this farmer area
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the ID of this farmer area.
     *
     * @return the ID of this farmer area
     */
    public long getId();

    /**
     * Sets the ID of this farmer area.
     *
     * @param id the ID of this farmer area
     */
    public void setId(long id);

    /**
     * Returns the farmer ID of this farmer area.
     *
     * @return the farmer ID of this farmer area
     */
    public long getFarmerId();

    /**
     * Sets the farmer ID of this farmer area.
     *
     * @param farmerId the farmer ID of this farmer area
     */
    public void setFarmerId(long farmerId);

    /**
     * Returns the area ID of this farmer area.
     *
     * @return the area ID of this farmer area
     */
    public long getAreaId();

    /**
     * Sets the area ID of this farmer area.
     *
     * @param areaId the area ID of this farmer area
     */
    public void setAreaId(long areaId);

    /**
     * Returns the description of this farmer area.
     *
     * @return the description of this farmer area
     */
    @AutoEscape
    public String getDescription();

    /**
     * Sets the description of this farmer area.
     *
     * @param description the description of this farmer area
     */
    public void setDescription(String description);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(agrar.farmer.sbuilder.model.FarmerArea farmerArea);

    @Override
    public int hashCode();

    @Override
    public CacheModel<agrar.farmer.sbuilder.model.FarmerArea> toCacheModel();

    @Override
    public agrar.farmer.sbuilder.model.FarmerArea toEscapedModel();

    @Override
    public agrar.farmer.sbuilder.model.FarmerArea toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
