package agrar.dict.sbuilder.model.impl;

import agrar.dict.sbuilder.model.DictArea;
import agrar.dict.sbuilder.service.DictAreaLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the DictArea service. Represents a row in the &quot;agrar_dict_DictArea&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DictAreaImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DictAreaImpl
 * @see agrar.dict.sbuilder.model.DictArea
 * @generated
 */
public abstract class DictAreaBaseImpl extends DictAreaModelImpl
    implements DictArea {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a dict area model instance should use the {@link DictArea} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            DictAreaLocalServiceUtil.addDictArea(this);
        } else {
            DictAreaLocalServiceUtil.updateDictArea(this);
        }
    }
}
